### ISSUE TITLE
File Editor

### ISSUE THREAD

**Issue by spenc53** [spenc53/pystudio_electron#3]
Add file editor to the top left area of the project.

Requirements:
- syntax highlighting
- copy paste
- execute code

**Comment by StevenSeeger** [comment]
I got the basic syntax highlighting. Later, I want to explore more in depth syntax highlight (ie from imported libraries).

**Comment by spenc53** [comment]
Sounds good, we will have the file editor shown now and we will add issues for file open and code execution.

**Comment by StevenSeeger** [comment]
Still have to add copy and pasta, along with code execution

**Comment by spenc53** [comment]
I created a new issue for this
