### ISSUE TITLE
Execute code from the file editor

### ISSUE THREAD

**Issue by spenc53** [spenc53/pystudio_electron#8]
When pressing command + r / control + r execute code.

You will need the juptyerMessagingService passed in via the props (check the terminal / plots for an example).

you will then be able to call the juptyerMessagingService.send(code) with the code that is highlighted.

Requirements:
- selected code runs when the Run key bindings are hit

**Comment by StevenSeeger** [comment]
Why is this control+r instead of control+enter?

**Comment by spenc53** [comment]
Um.... idk in my mind r = run. But, do whatever rstudio uses

**Comment by spenc53** [comment]
Eventually we will probably let users define these key bindings
